### ISSUE TITLE
ISP 2: ISCN core metadata specification

### ISSUE THREAD

**Issue by Aludirk** [likecoin/iscn-specs#2]
```
ISP: 2
Title: ISCN core metadata specification
Status: Draft
Created: 2020-03-26
Edited: 2020-04-25
```

## Motivation
![ISCN architecture](https://gateway.pinata.cloud/ipfs/QmaMYSom3o3UUTvdqyV8yMDLgU4XLmxz9WMjW8FWvPTkUq)

Based on the ISCN architecture, the ISCN core metadata acts as a kernel of ISCN, and it connects the content itself, the stakeholders and the license with a globally unique identifier. To achieve this objective, first of all, we need to define the format of the ISCN. After that, we need to define the identifier, some core metadata, and how to link to content metadata, stakeholders and license.

### Schema 
ISCN uses [JSON](https://www.json.org/) as encodings of the data, and the schema is as following:

Property|Occurs|Expected Type|Description
--|--|--|--
context|1|URL|The context should be an URL to the schema definition, to be confirmed when this proposal is in the final stage.
id|1|String|This is the identifier of ISCN, and it is in the format:<br>`<registry-code>/<unique-id>[/<version>]`<br><br>`registry-code`: The reserved code for a [registry](#registry).<br>`unique-id`: Any string contains alphanumeric and hyphens which is `[a-z][A-Z][0-9]-`,  provided that is unique within the given [registry](#registry).<br>`version`: Once the digital content is registered, the version counts as **1**. When there is any update later, the version number will go up one by one. Whenever the version is going up, the `registry-code` and `unique-id` must keep the same. Otherwise, it is an invalid ISCN. The version is optional, and if it does not provide, it means the latest version.<br><br>For example:<br>`1/abc-xyz-123`: Latest version of the ID `abc-xyz-123` and from registry 1<br>`2/music-010-1234/3`: Version 3 of the ID `music-010-1234` and from registry 2.
timestamp |1|DateTime|The timestamp of the creation or the modification of the ISCN record. It should be a human-readable DateTime and recommends to use ISO 8601.
version|1|Number|Once the digital content is registered, the version counts as **1**. When there is any update later, the version number will go up one by one.
parent|0<sup>*</sup>~1|[Linked Data](#linked-data)|The link to the previous version of the ISCN record which means the `registry-code` and `unique-id` in ISCN ID must be same. Otherwise, it counts as an invalid ISCN record.<br><br>*\* Only if the version is **1**, otherwise parent must be linked.*
rights|1|[Linked Data](#linked-data)|The link to the information of intellectual property rights. (Define in the coming proposal.)
stakeholders|1|[Linked Data](#linked-data)|The link to an array of information of stakeholders. (Define in the coming proposal.)
content|1|[Linked Data](#linked-data)|The link to the content metadata. (Define in the coming proposal.)

### <a name="registry">Registry</a>
A registry is a service provider for the ISCN registration, and a registry should provide service to register a digital content with metadata that follows the ISCN specification and to query. If any entities want to become a registry for ISCN, they should reserve a code for their registry in [here](https://github.com/likecoin/iscn-registry).

### <a name="linked-data">Linked Data</a>
Linked data is structured data that can be looked up via some methods, HTTP, RDF and URI but not limited to are all accepted.

**Comment by Aludirk** [comment]
Change `version` to `context` to unify among all schema.
Find the diff in [here](https://github.com/likecoin/iscn-specs/wiki/ISP-2:-ISCN-core-metadata-specification/_compare/45a4743771ead98ad24a74b248b173ec4ee5f0e5...c76c320e6366c5223ae6e8ed121d61a00101cab9).

**Comment by Aludirk** [comment]
Rename `edition` to `version` to separate the concepts between the version of ISCN and the edition of content.
Find the diff in [here](https://github.com/likecoin/iscn-specs/wiki/ISP-2:-ISCN-core-metadata-specification/_compare/c76c320e6366c5223ae6e8ed121d61a00101cab9...5a47b5aa522197cf6d1c042a49077ce04e783559?diff=unified).

**Comment by nnkken** [comment]
Since `stakeholder` is actually an array, and probably will contain more than 1 record in most cases, I suggest to use plural form `stakeholders` instead.

Also, according to #4 , `license` should be renamed to `right` or `rights`.

**Comment by Aludirk** [comment]
1. Rename`stakeholder` to `stakeholders`
1. Rename `license` to `rights`

Find the diff in [here](https://github.com/likecoin/iscn-specs/wiki/ISP-2:-ISCN-core-metadata-specification/_compare/5a47b5aa522197cf6d1c042a49077ce04e783559...e3a98ff6b17edf81c13825626ee621fddf62ffc6).
