### ISSUE TITLE
ISP 3: ISCN stakeholder metadata specification

### ISSUE THREAD

**Issue by Aludirk** [likecoin/iscn-specs#3]
```
ISP: 3
Title: ISCN stakeholder metadata specification
Status: Draft
Created: 2020-04-02
Edited: 2020-06-17
```

## Motivation
ISCN stakeholder metadata stores the metadata of different stakeholders of digital content, including creator, contributor, editor, publisher and the stakeholders from underlying works which is the footprint of the digital content. This proposal is going to define the schema for such metadata.

## Proposal
Taking into account the information of the stakeholders are always reused, stakeholder should be an independent entity. Hence, we need to hold a list of stakeholders.

#### Stakeholders
The [Stakeholders](#stakeholders) holds a list of stakeholders and defines the ratio of profit sharing to each of the stakeholders.

#####  <a name="stakeholders">Stakeholders</a>
Property|Occurs|Expected Type|Description
--|--|--|--
context|1|URL|The context should be an URL to the schema definition, to be confirmed when this proposal is in the final stage.
stakeholders|1|Array of [StakeholderInfo](#stakeholderinfo)|An array of [StakeholderInfo](#stakeholderinfo).

##### <a name="stakeholderinfo">StakeholderInfo</a>
Property|Occurs|Expected Type|Description
--|--|--|--
type|1|String|The type is one of the following:<br><ul><li>`Creator`</li><li>`Contributor`</li><li>`Editor`</li><li>`Publisher`</li><li>`FootprintStakeholder`</li></ul>
stakeholder|1|Linked Data to [Entity](#entity)|A linked data to the [Entity](#entity) that describes the stakeholder.
sharing|1|Number|The hint on the weighting of the profit-sharing, the value is an arbitrary non-negative integer. The ratio of the weightings among all stakeholders can be a reference for the profit-sharing distribution.
footprint|0~1<sup>*</sup>|ISCN \| URI|An ISCN id or any valid URI that link to the underlying work of the digital content.<br><br>*\* If the `type` is `FootprintStakeholder`, the `footprint` property must be provided and link back to the underlying work.*

#### Entity
The [Entity](#entity) describes the basic information of an entity, and all specific entity should inherit from [Entity](#entity) to extend.

##### <a name="entity">Entity</a>
Property|Occurs|Expected Type|Description
--|--|--|--
context|1|URL|The context should be an URL to the schema definition, to be confirmed when this proposal is in the final stage.
id|1|String \| URI|The `id` property represents any kind of identifier for everything, and it should represent in either as String or URI links.
name|0~1|String|The `name` shows the display name of the entity.
description|0~1|String|The `description` shows a brief description of the entity.

**Comment by nnkken** [comment]
I suggest that `StakeholderInfo.sharing` change to non-negative integer instead of decimal for the following reasons:

First, decimal is somehow hard to implement (correctly).

Second, using integer means that there is no hard requirement that the numbers must add up to 1, which may be useful for some cases, e.g. for 1:2 sharing distribution, decimal will be 0.333333... and 0.666666..., which may cause loss of accuracy.

**Comment by Aludirk** [comment]
It sounds make sense, and I redefine the meaning of `sharing`.
Find the diff in [here](https://github.com/likecoin/iscn-specs/wiki/ISP-3:-ISCN-stakeholder-metadata-specification/_compare/5bd11074822ae2d4e01b7d0bd33f5ec38554df3d...436b07661e5ed6d2326231418e909361aef70658).
