### ISSUE TITLE
ISP 5: ISCN content metadata specification

### ISSUE THREAD

**Issue by Aludirk** [likecoin/iscn-specs#5]
```
ISP: 5
Title: ISCN content metadata specification
Status: Draft
Created: 2020-04-08
Edited: 2020-04-25
```

## Motivation
ISCN content metadata records the metadata of the digital content itself. Since the diversity among different types of digital content, each type of digital content should define their schema. This proposal is going to define the basic metadata that common between various types of digital content. Any other specific content metadata should extend from this schema.

### <a name="contentinfo">ContentInfo</a>
The [ContentInfo](#contentinfo) contains the necessary metadata of digital content, including the fingerprint, the source location and the title & description of the digital content.

Property|Occurs|Expected Type|Description
--|--|--|--
context|1|URL|The context should be an URL to the schema definition, to be confirmed when this proposal is in the final stage.
type|1|String|The type of digital content. The specific type of digital content should define this value.
version|1|Number|Once the content metadata is registered, the version counts as **1**. When there is any update later, the version number will go up one by one.
parent|0<sup>*</sup>~1|[Linked Data](#linked-data)|The link to the previous version of the content metadata.<br><br>*\* Only if the version is **1**, otherwise parent must be linked.*
source|0~1|URL|An URL to locate the source of digital content.
edition|0~1|String|The edition of digital content. It can be any kind of string that the creator to choose.
fingerprint|1|String \| Object|The fingerprint of digital content. The ISCN registry should define the precise algorithm used for each type of digital content. For example, it can be a particular cryptographic hash operation on the source file of the digital content or any newly defined data structure for the specific type of content. The chosen algorithm requires that it is a cryptographically strong hash function.
feature|0~1|String \| Object|The `feature` is another fingerprint of content, which, unlike the cryptographic fingerprint, does not apply to the specific encoding of the file. Instead, it extracts the features of the content by some content-specific characteristics. For example, the feature field of an article could be an encoded vector of the keywords of that article.
title|1|String|A title or a name of the digital content, and it recommends to keep in short.
description|0~1|String|A brief description to introduce the digital content.
tags|0~1|Array of String|A list of hashtags/keywords of the digital content.

**Comment by guoliu** [comment]
I think content version will be a commonly used feature, especially when fingerprint is supported, since fingerprint changes upon version update. Maybe a field recording current version number, and a field recording the previous version or version history can fulfill this need?

**Comment by Aludirk** [comment]
Yes, you are right.

We need to record the edition of the content metadata and history, but what do you think how to define edition? Is edition should bound to the fingerprint that means only the change of fingerprint leads the edition to increase? Or the edition means all of the changes in content metadata?

I prefer the latter.

**Comment by nnkken** [comment]
I think for version (content metadata's version), the registry needs to increment it when there is update on content metadata.
But for edition (content's version), it should be defined by the content creator.
For example, if I'm a textbook writer who wrote a textbook which was published 10 years ago and already evolved to 3rd edition, then when I upload it to an ISCN registry, I would like to claim that the content edition is 3.
Then maybe a few years after, the edition evolved to 5, and someone remind me to update the ISCN record. Although I should be uploading both edition 4 and 5, I think the registry should allow me to skip edition 4 and upload edition 5 directly instead.

**Comment by Aludirk** [comment]
So, I can add three properties:
`version`: The version of content metadata, any changes of content metadata will lead the `version` +1
`parent`: Link to previous content metadata, `version` should -1, no this property if `version` is 1
`edition`: An number? A string? to represent the edition of the content itself

any comments?

**Comment by ckxpress** [comment]
think `edition` as a string is more flexible, since it's not auto increment anyway.

**Comment by Aludirk** [comment]
Add `version`, `parent` and `edition`.
Find the diff in [here](https://github.com/likecoin/iscn-specs/wiki/ISP-5:-ISCN-content-metadata-specification/_compare/d0b734360da1ecd48af436f123dd7b7a02092092...54e60dfdbd82ad2bd86cda61ec83d0c98424c18b?diff=split).

**Comment by lancatlin** [comment]
Where to record the author? Recording by who submits this transaction? How about multiple authors?
